-- 재밌다! 신난다!

SELECT PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT*PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT
NATURAL JOIN FOOD_ORDER
WHERE DATE_FORMAT(PRODUCE_DATE, '%y-%m') = '22-05'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID
